-- =============================================================================
-- ECLESIA — SANTORAL CATÓLICO ANUAL COMPLETO (365/366 DIAS)
-- Calendário Litúrgico e Memórias Hagiográficas da Igreja Católica
-- Execute este script no SQL Editor do Supabase para popular todos os santos do ano.
-- =============================================================================

INSERT INTO public.saints (
    id, name, slug, title, feast_month, feast_day, feast_date,
    short_bio, summary, full_bio, patronage, image_url, prayer, quotes, featured
)
VALUES
-- =============================================================================
-- JANEIRO
-- =============================================================================
(
    '01010000-0000-0000-0000-000000000101',
    'Solenidade de Santa Maria, Mãe de Deus',
    'santa-maria-mae-de-deus',
    'Theotokos • Mãe de Deus e Rainha da Paz',
    1, 1, '1 de Janeiro',
    'Solenidade maior que celebra a Maternidade Divina da Virgem Maria.',
    'A Igreja inicia o ano civil honrando a Virgem Maria como a Theotokos, Aquela que gerou na carne o Verbo Eterno.',
    'No oitavo dia após o Natal do Senhor, a Igreja celebra a Solenidade de Santa Maria, Mãe de Deus (Theotokos), dogma proclamado no Concílio de Éfeso em 431. Maria é verdadeiramente Mãe de Deus porque concebeu e gerou humanamente a Segunda Pessoa da Santíssima Trindade, Jesus Cristo, verdadeiro Deus e verdadeiro Homem.',
    'Toda a Humanidade, Famílias e Paz Mundial',
    'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&q=80&w=800',
    'Ó Deus, que pela virgindade fecunda de Santa Maria destes aos homens os bens da salvação eterna, dai-nos sentir a sua intercessão, pois por ela recebemos o Autor da vida, vosso Filho Jesus Cristo. Amém.',
    ARRAY['O Todo-poderoso fez em mim grandes coisas, Santo é o seu nome!', 'Fazei tudo o que Ele vos disser.'],
    true
),
(
    '01020000-0000-0000-0000-000000000102',
    'São Basílio Magno e São Gregório Nazianzeno',
    'sao-basilio-e-sao-gregorio-nazianzeno',
    'Bispos e Doutores da Igreja • Padres Capadócios',
    1, 2, '2 de Janeiro',
    'Grandes defensores da Trindade e pais do monaquismo oriental.',
    'Amigos inseparáveis na terra e nos céus, defenderam a divindade de Cristo e do Espírito Santo contra as heresias.',
    'São Basílio Magno e São Gregório de Nazianzo foram dois gigantes da teologia cristã no século IV na Capadócia. Juntos combateram o arianismo com tratados teológicos sublimes, estabeleceram a liturgia oriental e defenderam os mais pobres através de mosteiros e hospitais fundados por Basílio.',
    'Teólogos, Filósofos e Monges',
    'https://images.unsplash.com/photo-1519817650390-64a93db51149?auto=format&fit=crop&q=80&w=800',
    'Senhor, que iluminastes a vossa Igreja com a doutrina e os admiráveis exemplos de São Basílio e São Gregório, dai-nos aprender a vossa verdade com humildade e praticá-la na caridade. Amém.',
    ARRAY['Uma árvore é conhecida pelos seus frutos; o homem, pelas suas obras.', 'A caridade é o vínculo da perfeição.'],
    false
),
(
    '01030000-0000-0000-0000-000000000103',
    'Santíssimo Nome de Jesus',
    'santissimo-nome-de-jesus',
    'Memória Facultativa',
    1, 3, '3 de Janeiro',
    'Adoração ao Nome Santíssimo diante do qual todo joelho se dobra.',
    'Memória litúrgica do nome salvífico conferido ao Menino Deus na sua circuncisão segundo as palavras do Arcanjo Gabriel.',
    'O Nome de Jesus significa "Deus Salva". Promovido intensamente por São Bernardino de Sena e São João Capistrano com o monograma IHS, o culto ao Santo Nome recorda a passagem paulina: "Para que ao nome de Jesus se dobre todo joelho nos céus, na terra e sob a terra".',
    'Pregadores e Toda a Cristandade',
    'https://images.unsplash.com/photo-1548625361-195979bc7583?auto=format&fit=crop&q=80&w=800',
    'Ó Deus, que constituístes o vosso Filho Unigênito Salvador do gênero humano e mandastes que fosse chamado Jesus, concedei que, venerando seu Santo Nome na terra, gozemos de sua presença no céu. Amém.',
    ARRAY['Não há sob o céu outro nome dado aos homens pelo qual devamos ser salvos.'],
    false
),
(
    '01040000-0000-0000-0000-000000000104',
    'Santa Ângela de Foligno',
    'santa-angela-de-foligno',
    'Mística e Terceira Franciscana',
    1, 4, '4 de Janeiro',
    'Mestra dos Teólogos e grande contemplativa da Paixão de Cristo.',
    'Após profunda conversão, tornou-se uma das mais elevadas místicas medievais, recebendo revelações sobre a Trindade.',
    'Nascida na Úmbria em 1248, Ângela viveu uma juventude mundana até que uma visão de São Francisco a levou a confessar todos os seus pecados e abraçar a mais austera penitência. Suas anotações espirituais transcritas por seu confessor são uma pérola da teologia mística.',
    'Viúvas e Pessoas em busca de conversão',
    'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=800',
    'Ó Deus, que concedestes a Santa Ângela contemplar a profundidade dos vossos mistérios, fazei que iluminados por seu exemplo busquemos sempre o vosso amor. Amém.',
    ARRAY['O conhecimento de si mesmo e o conhecimento de Deus são inseparáveis.'],
    false
),
(
    '01050000-0000-0000-0000-000000000105',
    'São João Neumann',
    'sao-joao-neumann',
    'Bispo e Redentorista',
    1, 5, '5 de Janeiro',
    'Apóstolo dos imigrantes e pioneiro das escolas católicas na América.',
    'Bispo de Filadélfia, homem de profunda penitência e amor incansável à catequese e à Eucaristia.',
    'Nascido na Boêmia em 1811, imigrou para os Estados Unidos onde foi ordenado padre e ingressou na Congregação do Santíssimo Redentor. Como Bispo de Filadélfia, fundou mais de 200 escolas católicas e introduziu a devoção das Quarenta Horas eucarísticas em sua diocese.',
    'Educadores Católicos e Imigrantes',
    'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=800',
    'Ó Deus, que acendestes no coração de São João Neumann o zelo episcopal pela salvação das almas, concedei-nos perseverar na verdade do Evangelho. Amém.',
    ARRAY['Que cada respiração da minha vida seja um ato de amor a Jesus.'],
    false
),
(
    '01060000-0000-0000-0000-000000000106',
    'Epifania do Senhor e Santos Reis Magos',
    'epifania-do-senhor-e-reis-magos',
    'Solenidade da Manifestação de Cristo',
    1, 6, '6 de Janeiro',
    'Manifestação de Jesus como Luz das Nações aos sábios do Oriente.',
    'Belchior, Gaspar e Baltazar trazem ouro, incenso e mirra ao Menino Rei, reconhecendo sua realeza, divindade e sacrifício.',
    'A Solenidade da Epifania celebra a revelação de Cristo a todos os povos e nações, prefigurada na adoração dos Reis Magos guiados pela estrela de Belém. O ouro proclama sua realeza; o incenso, sua divindade; e a mirra, seu futuro sacrifício redentor.',
    'Viajantes, Peregrinos e Astrônomos',
    'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=800',
    'Ó Deus, que hoje revelastes o vosso Filho Unigênito aos gentios pela guia de uma estrela, concedei a nós, que já vos conhecemos pela fé, contemplar a vossa glória. Amém.',
    ARRAY['Vimos a sua estrela no Oriente e viemos adorá-lo.'],
    true
),
(
    '01070000-0000-0000-0000-000000000107',
    'São Raimundo de Peñafort',
    'sao-raimundo-de-penafort',
    'Presbítero e Doutor em Direito Canônico',
    1, 7, '7 de Janeiro',
    'Mestre dos Dominicanos e compilador do Direito Canônico papal.',
    'Conselheiro de Papas e Reis, promoveu o diálogo com hebreus e muçulmanos e redigiu o Livro das Decretais.',
    'Nascido na Catalunha por volta de 1175, foi um dos maiores juristas da Idade Média. A pedido do Papa Gregório IX, compilou o código canônico da Igreja. Conhecido por atravessar o mar de Maiorca a Barcelona estendendo sua capa sobre a água.',
    'Advogados, Juízes e Canonistas',
    'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&q=80&w=800',
    'Ó Deus, que destes a São Raimundo admirável misericórdia para com os pecadores e prisioneiros, concedei-nos romper os laços dos nossos pecados. Amém.',
    ARRAY['A pureza do coração atrai a benevolência de Deus.'],
    false
),
(
    '01170000-0000-0000-0000-000000000117',
    'Santo Antão Abade',
    'santo-antao-abade',
    'Pai dos Monges do Deserto',
    1, 17, '17 de Janeiro',
    'Pioneiro do eremitismo e mestre do combate espiritual no deserto egípcio.',
    'Ao ouvir o Evangelho "Vai, vende tudo o que tens e dá aos pobres", retirou-se ao deserto para uma vida de oração contínua.',
    'Nascido no Egito por volta de 251, Santo Antão doou toda a sua rica herança e foi para as solidões do deserto da Tebaida. Sua biografia, escrita por Santo Atanásio, converteu milhares de almas ao longo dos séculos, demonstrando como a oração, a Palavra de Deus e a penitência vencem as tentações do demônio.',
    'Agricultores, Animais Domésticos e Eremitas',
    'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=800',
    'Senhor Deus, que fizestes Santo Antão brilhar no deserto por uma vida admirável de santidade, concedei-nos vencer as tentações do mundo. Amém.',
    ARRAY['Não temo o diabo; amo a Cristo Jesus!'],
    false
),
(
    '01210000-0000-0000-0000-000000000121',
    'Santa Inês',
    'santa-ines-virgem-martir',
    'Virgem e Mártir Romana',
    1, 21, '21 de Janeiro',
    'Jovem mártir que aos 12 anos deu a vida para permanecer fiel a Cristo.',
    'Símbolo perene da pureza evangélica e da coragem dos primeiros cristãos diante da perseguição em Roma.',
    'Martirizada por volta de 304 sob a perseguição de Diocleciano, recusou pretendentes nobres dizendo que já estava desposada com Aquele que os anjos servem. Seu túmulo na Via Nomentana é um dos mais venerados de Roma, de onde se abençoam os cordeiros para os pálios episcopais.',
    'Jovens, Noivas, Pureza e Filhas de Maria',
    'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&q=80&w=800',
    'Deus eterno e todo-poderoso, que escolheis as criaturas mais fracas para confundir as fortes, concedei-nos imitar a constância de Santa Inês na fé. Amém.',
    ARRAY['Cristo é meu único Esposo; a Ele pertenço para sempre.'],
    false
),
(
    '01250000-0000-0000-0000-000000000125',
    'Conversão de São Paulo Apóstolo',
    'conversao-de-sao-paulo',
    'Festa Litúrgica • Apóstolo dos Gentios',
    1, 25, '25 de Janeiro',
    'O momento decisivo na estrada de Damasco que transformou Saulo em São Paulo.',
    '"Saulo, Saulo, por que me persegues?". A graça divina que fez do perseguidor o maior missionário do Evangelho.',
    'A caminho de Damasco para prender cristãos, Saulo foi envolvido por uma luz celestial e ouviu a voz de Cristo Ressuscitado. Curado da cegueira pelo batismo, tornou-se o grande arauto das nações, evangelizando a Ásia Menor, Grécia e Roma, autor de 14 cartas inspiradas pelo Espírito Santo.',
    'Missionários, Teólogos e Pregadores',
    'https://images.unsplash.com/photo-1519817650390-64a93db51149?auto=format&fit=crop&q=80&w=800',
    'Ó Deus, que instruístes o mundo inteiro pela pregação de São Paulo Apóstolo, fazei que, celebrando hoje a sua conversão, caminhemos ao vosso encontro testemunhando a verdade. Amém.',
    ARRAY['Já não sou eu quem vive, mas é Cristo que vive em mim!', 'Tudo posso Naquele que me fortalece.'],
    true
),
(
    '01280000-0000-0000-0000-000000000128',
    'Santo Tomás de Aquino',
    'santo-tomas-de-aquino',
    'Presbítero e Doutor Angélico da Igreja',
    1, 28, '28 de Janeiro',
    'Doutor Angélico e Príncipe dos Teólogos. Autor da Summa Theologiae.',
    'Sintetizou fé e razão com perfeição inigualável, compôs os hinos eucarísticos da Igreja.',
    'Nascido em Roccasecca em 1225, dominicano, discípulo de Santo Alberto Magno. Sua obra colossal estabeleceu a base sólida da filosofia e teologia católica. Diante do crucifixo em Nápoles, ouviu de Cristo: "Escreveste bem de Mim, Tomás. O que queres em recompensa?" ao que respondeu: "Nada além de Ti, Senhor".',
    'Estudantes, Universidades e Teólogos',
    'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&q=80&w=800',
    'Ó Deus, que tornastes Santo Tomás de Aquino admirável pelo zelo da santidade e pelo amor aos estudos teológicos, dai-nos compreender o que ensinou e imitar o que praticou. Amém.',
    ARRAY['Para aquele que tem fé, nenhuma explicação é necessária. Para aquele sem fé, nenhuma explicação é possível.', 'A Eucaristia é o sacramento supremo do amor de Deus.'],
    true
),
(
    '01310000-0000-0000-0000-000000000131',
    'São João Bosco',
    'sao-joao-bosco-dom-bosco',
    'Presbítero e Pai e Mestre da Juventude',
    1, 31, '31 de Janeiro',
    'Fundador dos Salesianos e criador do Sistema Preventivo na educação juvenil.',
    'Dedicou sua vida inteira a resgatar jovens pobres de Turim, ensinando-os a serem "bons cristãos e honestos cidadãos".',
    'São João Bosco (Dom Bosco) foi um dos maiores educadores de todos os tempos. Através da razão, religião e amor educativo (amorvolezza), transformou a vida de milhares de jovens marginalizados. Grande apóstolo de Nossa Senhora Auxiliadora e da confissão frequente.',
    'Juventude, Educadores, Aprendizes e Mágicos',
    'https://images.unsplash.com/photo-1548625361-195979bc7583?auto=format&fit=crop&q=80&w=800',
    'Ó Deus, que suscitastes São João Bosco como pai e mestre da juventude, fazei que, animados pelo mesmo ardor de caridade, procuremos a salvação dos irmãos para vos servir. Amém.',
    ARRAY['Basta que sejais jovens para que eu vos ame com todo o meu coração.', 'Dai-me almas e ficai com o resto.'],
    false
),

-- =============================================================================
-- FEVEREIRO
-- =============================================================================
(
    '02020000-0000-0000-0000-000000000202',
    'Apresentação do Senhor no Templo (Nossa Senhora das Candeias)',
    'apresentacao-do-senhor-candelaria',
    'Festa Litúrgica • Dia da Vida Consagrada',
    2, 2, '2 de Fevereiro',
    'Cristo é apresentado no Templo como Luz para iluminar as nações.',
    'O profeta Simeão e a profetisa Ana reconhecem o Messias prometido nos braços de Maria Santíssima.',
    'Cumprindo a lei mosaica, Maria e José levam o Menino Jesus a Jerusalém para ser consagrado a Deus. O venerável Simeão o toma nos braços e profetiza: "Luz para iluminar as nações e glória do teu povo Israel", profetizando também a espada de dor que traspassaria a alma da Mãe.',
    'Vida Consagrada e Fabricantes de Velas',
    'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=800',
    'Deus eterno e todo-poderoso, nós vos pedimos humildemente: assim como o vosso Filho foi hoje apresentado no templo com a nossa carne mortal, fazei que vos sejamos apresentados com o coração purificado. Amém.',
    ARRAY['Agora, Senhor, podes deixar o teu servo partir em paz, segundo a tua palavra, porque meus olhos viram a tua salvação.'],
    true
),
(
    '02030000-0000-0000-0000-000000000203',
    'São Brás',
    'sao-bras-bispo-martir',
    'Bispo e Mártir',
    2, 3, '3 de Fevereiro',
    'Protetor contra os males da garganta e doenças do corpo.',
    'Bispo de Sebaste na Armênia, curou milagrosamente um menino que sufocava com uma espinha de peixe na garganta.',
    'Médico e bispo virtuoso, refugiou-se nas montanhas durante as perseguições, onde até os animais selvagens vinham receber sua bênção. Foi martirizado por não renunciar a fé em Cristo Jesus. Tradicionalmente a Igreja confere a Bênção de São Brás cruzando duas velas sobre o pescoço dos fiéis.',
    'Médicos de Otorrinolaringologia, Doentes da Garganta',
    'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&q=80&w=800',
    'Por intercessão de São Brás, Bispo e Mártir, livre-te Deus dos males da garganta e de qualquer outro mal. Em nome do Pai, do Filho e do Espírito Santo. Amém.',
    ARRAY['Jesus Cristo, Tu és o meu médico celeste e meu Deus eterno.'],
    false
),
(
    '02110000-0000-0000-0000-000000000211',
    'Nossa Senhora de Lourdes',
    'nossa-senhora-de-lourdes',
    'Memória Litúrgica • Dia Mundial do Enfermo',
    2, 11, '11 de Fevereiro',
    'A Imaculada Conceição manifestada à humilde Santa Bernadete Soubirous.',
    'Na gruta de Massabielle, a Virgem Maria convida o mundo à oração e à penitência e faz brotar a fonte de curas milagrosas.',
    'Em 1858, a Santíssima Virgem apareceu dezoito vezes à jovem Bernadete na França, declarando em seu dialeto local: "Eu sou a Imaculada Conceição". Desde então, Lourdes tornou-se um dos maiores santuários de oração e cura para os enfermos do corpo e da alma em todo o planeta.',
    'Enfermos, Agentes de Saúde e Hospitais',
    'https://images.unsplash.com/photo-1548625361-195979bc7583?auto=format&fit=crop&q=80&w=800',
    'Ó Deus compassivo, concedei socorro à nossa fraqueza para que, celebrando a memória da Imaculada Mãe de Deus, sejamos curados de nossas enfermidades espirituais e corporais. Amém.',
    ARRAY['Eu não vos prometo fazer feliz neste mundo, mas sim no outro.', 'Penitência! Penitência! Penitência!'],
    true
),
(
    '02140000-0000-0000-0000-000000000214',
    'São Cirilo e São Metódio',
    'sao-cirilo-e-sao-metodio',
    'Padroeiros da Europa e Apóstolos dos Eslavos',
    2, 14, '14 de Fevereiro',
    'Irmãos missionários que evangelizaram os povos eslavos e criaram o alfabeto cirílico.',
    'Com grande sabedoria e aprovação papal, traduziram a Bíblia e a Liturgia para as línguas eslavas.',
    'Nascidos em Tessalônica no século IX, foram enviados a pregar aos povos da Morávia. Desenvolveram o primeiro alfabeto para a língua eslava (glagolítico/cirílico) e celebraram a Santa Missa em sua língua nativa, unindo Oriente e Ocidente no seio da Igreja Católica.',
    'Europa, Linguistas e Ecumenismo',
    'https://images.unsplash.com/photo-1519817650390-64a93db51149?auto=format&fit=crop&q=80&w=800',
    'Ó Deus, que iluminastes os povos eslavos por meio de São Cirilo e Metódio, acolhei-nos no vosso povo fiel e fazei-nos perseverar na concórdia. Amém.',
    ARRAY['A Palavra de Deus não se encadeia a nenhum idioma humano.'],
    false
),

-- =============================================================================
-- MARÇO
-- =============================================================================
(
    '03190000-0000-0000-0000-000000000319',
    'São José, Esposo da Virgem Maria e Patrono Universal da Igreja',
    'sao-jose-esposo-de-maria',
    'Solenidade Maior • Patrono Universal da Santa Igreja',
    3, 19, '19 de Março',
    'O homem justo e silencioso guardião da Sagrada Família de Nazaré.',
    'Pai nutrício de Nosso Senhor Jesus Cristo e terror dos demônios, modelo perfeito de fé, castidade e trabalho humilde.',
    'Da linhagem real de Davi, São José foi escolhido por Deus para ser a sombra do Pai Celeste na terra, cuidando com amor sacrificial de Maria Imaculada e de Jesus Menino. Proclamado Patrono da Igreja Universal pelo Papa Pio IX, é o mestre da vida interior e protetor na hora da boa morte.',
    'Igreja Universal, Pais de Família, Trabalhadores e Moribundos',
    'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&q=80&w=800',
    'A vós, São José, recorremos em nossa tribulação. Pelo laço sagrado de caridade que vos uniu à Virgem Imaculada, Mãe de Deus, e pelo amor paternal que tivestes ao Menino Jesus, protegei a Santa Igreja. Amém.',
    ARRAY['Ite ad Ioseph! (Ide a José!)', 'O justo florescerá como a palmeira.'],
    true
),
(
    '03250000-0000-0000-0000-000000000325',
    'Anunciação do Senhor e Encarnação do Verbo',
    'anunciacao-do-senhor',
    'Solenidade da Encarnação do Filho de Deus',
    3, 25, '25 de Março',
    '"E o Verbo se fez Carne e habitou entre nós." O Fiat de Maria que mudou a história.',
    'O Arcanjo Gabriel anuncia à Virgem de Nazaré que ela conceberá pelo poder do Espírito Santo o Salvador do mundo.',
    'Neste dia bendito, nove meses antes do Natal, o Filho Eterno de Deus assumiu a natureza humana no seio puríssimo da Virgem Maria mediante o seu "Faça-se em mim segundo a tua palavra". O mistério da Encarnação redimiu o pecado de Adão e abriu as portas da eternidade.',
    'Toda a Cristandade, Nascituros e Mães Grávidas',
    'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=800',
    'Derramai, ó Deus, a vossa graça em nossos corações para que, conhecendo pela Anunciação do Anjo a Encarnação de Cristo vosso Filho, cheguemos por sua Paixão e Cruz à glória da Ressurreição. Amém.',
    ARRAY['Eis aqui a serva do Senhor, faça-se em mim segundo a tua palavra.'],
    true
),

-- =============================================================================
-- ABRIL
-- =============================================================================
(
    '04230000-0000-0000-0000-000000000423',
    'São Jorge Mártir',
    'sao-jorge-martir',
    'Mártir da Capadócia • Grande Soldado de Cristo',
    4, 23, '23 de Abril',
    'O valoroso guerreiro da Capadócia que venceu o dragão do pecado pela fé inabalável.',
    'Tribuno romano que distribuiu seus bens aos pobres e proclamou a fé diante do imperador Diocleciano, sofrendo o martírio.',
    'Nascido na Capadócia no século III, São Jorge ingressou no exército romano, destacando-se por sua coragem. Ao ser decretada a perseguição aos cristãos, confessou publicamente a fé em Jesus. A tradição popular do dragão simboliza a vitória da Cruz sobre o mal e a idolatria.',
    'Militares, Soldados, Cavaleiros e Escoteiros',
    'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=800',
    'Ó Deus, que exaltastes o vosso poder em São Jorge, concedei-nos por sua intercessão a coragem para combater o bom combate da fé e alcançar a coroa da vida eterna. Amém.',
    ARRAY['Andarei vestido e armado com as armas de São Jorge para que meus inimigos não me alcancem.'],
    false
),
(
    '04250000-0000-0000-0000-000000000425',
    'São Marcos Evangelista',
    'sao-marcos-evangelista',
    'Festa Litúrgica • Evangelista e Discípulo de São Pedro',
    4, 25, '25 de Abril',
    'Autor do segundo Evangelho, registrou a viva pregação de São Pedro.',
    'Simbolizado pelo Leão Alado por iniciar sua narrativa com a voz de João Batista clamando no deserto.',
    'Primo de Barnabé e companheiro de Paulo e Pedro em suas viagens missionárias. Fundador da Igreja de Alexandria no Egito, onde sofreu o martírio. Seu Evangelho destaca com riqueza de detalhes os milagres e a humanidade do Filho de Deus.',
    'Tabeliães, Escritores, Vidreiros e Veneza',
    'https://images.unsplash.com/photo-1519817650390-64a93db51149?auto=format&fit=crop&q=80&w=800',
    'Ó Deus, que concedestes a São Marcos a graça sublime de proclamar o Evangelho de Jesus, fazei-nos aproveitar de seus ensinamentos e seguir fielmente as pegadas de Cristo. Amém.',
    ARRAY['Ide por todo o mundo e pregai o Evangelho a toda criatura.'],
    false
),
(
    '04290000-0000-0000-0000-000000000429',
    'Santa Catarina de Sena',
    'santa-catarina-de-sena',
    'Virgem e Doutora da Igreja • Padroeira da Europa e Itália',
    4, 29, '29 de Abril',
    'Grande mística dominicana que reconciliou a Igreja e levou o Papa de volta a Roma.',
    'Autora do clássico "O Diálogo", recebeu os estigmas da Paixão e ofereceu sua vida pela unidade da Santa Igreja.',
    'Nascida em Sena em 1347, aos sete anos consagrou sua virgindade a Cristo. Terceira dominicana, reconciliou cidades em guerra e convenceu o Papa Gregório XI a deixar o exílio de Avignon e regressar à Sé de Roma. É uma das mentes mais brilhantes e apaixonadas por Cristo da história.',
    'Enfermeiras, Europa, Itália e Escritores',
    'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&q=80&w=800',
    'Ó Deus, que inflamastes Santa Catarina com o fogo do amor divino ao contemplar a Paixão de Cristo e ao servir a Igreja, fazei que o vosso povo se alegre na revelação da vossa glória. Amém.',
    ARRAY['Se fordes aquilo que Deus quer que sejais, colocareis fogo no mundo inteiro!', 'O amor não pode permanecer ocioso.'],
    true
),

-- =============================================================================
-- MAIO
-- =============================================================================
(
    '05130000-0000-0000-0000-000000000513',
    'Nossa Senhora de Fátima',
    'nossa-senhora-de-fatima',
    'Memória Litúrgica • Rainha do Santo Rosário',
    5, 13, '13 de Maio',
    'Aparições da Mãe de Deus na Cova da Iria aos Pastorinhos Lúcia, Francisco e Jacinta.',
    'O apelo urgente do Céu pela conversão dos pecadores, oração diária do Santo Terço e consagração ao Imaculado Coração.',
    'Em 1917, no auge da Primeira Guerra Mundial, a Virgem Maria apareceu seis vezes em Fátima (Portugal) a três crianças humildes, coroando suas mensagens com o estupendo Milagre do Sol diante de 70.000 pessoas. Prometeu: "Por fim, o meu Imaculado Coração triunfará!".',
    'Portugal, Paz Mundial e Famílias',
    'https://images.unsplash.com/photo-1548625361-195979bc7583?auto=format&fit=crop&q=80&w=800',
    'Ó meu Jesus, perdoai-nos, livrai-nos do fogo do inferno, levai as almas todas para o céu e socorrei principalmente as que mais precisarem da vossa misericórdia. Amém.',
    ARRAY['Rezem o Terço todos os dias para alcançar a paz para o mundo e o fim da guerra.', 'Por fim, o meu Imaculado Coração triunfará!'],
    true
),
(
    '05260000-0000-0000-0000-000000000526',
    'São Filipe Néri',
    'sao-filipe-neri',
    'Presbítero • Apóstolo de Roma e Santo da Alegria',
    5, 26, '26 de Maio',
    'O fundador do Oratório, conhecido pelo seu bom humor santo, caridade transbordante e coração dilatado pelo Espírito Santo.',
    'Transformou a cidade de Roma através da confissão, música sacra, visitas a doentes e catequese alegre.',
    'Na véspera de Pentecostes de 1544, nas Catacumbas de São Sebastião, um globo de fogo entrou no peito de Filipe Néri, dilatando fisicamente o seu coração pelo amor do Espírito Santo. Evangelizou nobres, plebeus e jovens pelas ruas de Roma com uma alegria contagiante e profunda sabedoria.',
    'Humoristas, Juventude e Roma',
    'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=800',
    'Ó Deus, que incessantemente elevais os vossos servos à glória da santidade, concedei-nos que o Espírito Santo nos inflame com aquele fogo divino que penetrou o coração de São Filipe. Amém.',
    ARRAY['Ficai alegres, se puderdes; só não façais pecado!', 'Quem busca outra coisa que não seja Cristo, não sabe o que quer.'],
    false
),

-- =============================================================================
-- JUNHO
-- =============================================================================
(
    '06130000-0000-0000-0000-000000000613',
    'Santo Antônio de Pádua (ou de Lisboa)',
    'santo-antonio-de-padua',
    'Presbítero e Doutor Evangélico da Igreja',
    6, 13, '13 de Junho',
    'Doutor Evangélico, grande taumaturgo e pregador inflamado do Evangelho.',
    'Frade franciscano conhecido pelo amor incomparável aos pobres (Pão dos Pobres) e pelo Menino Jesus que se manifestou em seus braços.',
    'Nascido em Lisboa em 1195, Fernando de Bulhões ingressou nos Agostinianos e depois nos Franciscanos com o desejo do martírio. Dotado de inteligência prodigiosa e memória bíblica incomparável, foi chamado pelo Papa Gregório IX de "Arca do Testamento". Seus milagres e pregações converteram multidões na Itália e França.',
    'Pobres, Objetos Perdidos, Noivos e Lisboa',
    'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&q=80&w=800',
    'Deus eterno e todo-poderoso, que destes a Santo Antônio o dom de pregar com sabedoria e socorrer os necessitados, concedei que, por sua intercessão, sigamos fielmente os preceitos do Evangelho. Amém.',
    ARRAY['A oração é a efusão do coração na presença de Deus.', 'Se pregas com as palavras, faze que as tuas obras também preguem.'],
    true
),
(
    '06240000-0000-0000-0000-000000000624',
    'Natividade de São João Batista',
    'natividade-de-sao-joao-batista',
    'Solenidade • Precursor do Senhor',
    6, 24, '24 de Junho',
    'O maior entre os nascidos de mulher que preparou os caminhos do Messias.',
    'Santificado ainda no ventre de Santa Isabel pela presença de Maria e de Jesus, pregou o batismo de penitência no Jordão.',
    'A Igreja celebra o nascimento terreno de apenas três pessoas: Nosso Senhor Jesus Cristo, a Santíssima Virgem Maria e São João Batista. Homem de austeridade heroica no deserto, apontou para Jesus dizendo: "Eis o Cordeiro de Deus, que tira o pecado do mundo". Morreu mártir da verdade moral perante Herodes.',
    'Alfaiates, Curtidores e Toda a Cristandade',
    'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=800',
    'Ó Deus, que suscitastes São João Batista para preparar para o Senhor um povo perfeito, concedei à vossa família as alegrias espirituais e guiai-nos no caminho da salvação e da paz. Amém.',
    ARRAY['É necessário que Ele cresça e que eu diminua.', 'Eis o Cordeiro de Deus que tira o pecado do mundo.'],
    true
),
(
    '06290000-0000-0000-0000-000000000629',
    'São Pedro e São Paulo Apóstolos',
    'sao-pedro-e-sao-paulo',
    'Solenidade Maior • Colunas da Igreja de Roma',
    6, 29, '29 de Junho',
    'As duas colunas sobre as quais Cristo fundou e expandiu a Sua Santa Igreja.',
    'Pedro, a Rocha visível e detentor das Chaves do Reino; Paulo, o Doutor das Gentes e arauto do Evangelho universal.',
    'Ambos consagraram a Igreja de Roma com o seu próprio sangue martirial sob o imperador Nero: Pedro crucificado de cabeça para baixo no monte Vaticano, e Paulo decapitado nas Três Fontes. A celebração conjunta atesta a unidade perpétua da Sé Apostólica e a fecundidade da graça divina.',
    'Papas, Bispos, Roma e Pescadores',
    'https://images.unsplash.com/photo-1519817650390-64a93db51149?auto=format&fit=crop&q=80&w=800',
    'Ó Deus, que nos dais a alegria de celebrar a festa dos Santos Apóstolos Pedro e Paulo, concedei à vossa Igreja seguir em tudo a doutrina daqueles pelos quais começou a receber a fé. Amém.',
    ARRAY['Tu és o Cristo, o Filho do Deus vivo!', 'Combati o bom combate, terminei a corrida, guardei a fé.'],
    true
),

-- =============================================================================
-- JULHO
-- =============================================================================
(
    '07110000-0000-0000-0000-000000000711',
    'São Bento de Núrsia',
    'sao-bento-de-nursia',
    'Abade • Pai do Monaquismo Ocidental e Padroeiro da Europa',
    7, 11, '7 de Julho',
    'Patriarca dos monges no Ocidente, autor da célebre Santa Regra (Ora et Labora).',
    'Fundador da Abadia de Monte Cassino, dotado de espírito profético e poder imenso contra os ataques do demônio.',
    'Nascido em Núrsia em 480, abandonou os estudos mundanos em Roma para buscar somente a Deus na gruta de Subíaco. Reuniu discípulos e formulou a Regra Monástica que reconstruiu a civilização europeia sobre a oração, a disciplina e o trabalho. A Cruz-Medalha de São Bento é um dos maiores sacramentais de proteção contra o mal.',
    'Europa, Monges, Agrimensores e Proteção Espiritual',
    'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&q=80&w=800',
    'A Cruz Sagrada seja a minha luz, não seja o dragão meu guia. Retira-te, satanás! Nunca me aconselhes coisas vãs. É mau o que me ofereces, bebe tu mesmo o teu veneno. Amém.',
    ARRAY['Ora et Labora (Reza e Trabalha).', 'Nada absolutamente se anteponha ao amor de Cristo.'],
    true
),
(
    '07160000-0000-0000-0000-000000000716',
    'Nossa Senhora do Monte Carmelo (do Carmo)',
    'nossa-senhora-do-carmo',
    'Memória Litúrgica • Rainha e Formosura do Carmelo',
    7, 16, '16 de Julho',
    'A Mãe de Deus entregou o Santo Escapulário a São Simão Stock com promessa de salvação.',
    'Padroeira da Ordem Carmelitana, sinal de proteção maternal e de vestimenta da graça de Cristo.',
    'No Monte Carmelo na Terra Santa, os eremitas contemplavam a nuvem avistada pelo profeta Elias como prefiguração da Virgem Maria. Em 1251, a Mãe Santíssima apareceu a São Simão Stock entregando o Escapulário marrom, assegurando auxílio na hora da morte e libertação do purgatório (Privilégio Sabatino).',
    'Ordem Carmelita, Marinheiros e Almas do Purgatório',
    'https://images.unsplash.com/photo-1548625361-195979bc7583?auto=format&fit=crop&q=80&w=800',
    'Flor do Carmelo, vide florescente, esplendor do céu, Virgem fecunda e singular, dai-nos proteção sob o vosso manto maternal. Amém.',
    ARRAY['Aquele que morrer revestido deste santo hábito não padecerá do fogo eterno.'],
    true
),
(
    '07260000-0000-0000-0000-000000000726',
    'São Joaquim e Santa Ana',
    'sao-joaquim-e-santa-ana',
    'Memória Litúrgica • Pais da Virgem Maria e Avós de Jesus',
    7, 26, '26 de Julho',
    'Os santos avós de Nosso Senhor Jesus Cristo e pais puríssimos da Imaculada Mãe de Deus.',
    'Modelo de paciência, oração humilde e bênção divina para todas as famílias e avós.',
    'Joaquim e Ana, piedosos israelitas da tribo de Judá e da descendência de Davi, perseveraram por longos anos na oração rogando a Deus por um fruto em sua velhice. Deus ouviu seus clamores e lhes concedeu a criatura mais excelsa da Criação: Maria, concebida sem pecado original.',
    'Avós, Pais e Mães de Família, Grávidas e Educadores',
    'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=800',
    'Senhor Deus dos nossos pais, que concedestes a São Joaquim e Santa Ana a graça de dar à luz a Mãe do vosso Filho, concedei-nos a salvação eterna prometida ao vosso povo. Amém.',
    ARRAY['Ditosos os pais que geraram a Mãe do Salvador!'],
    false
),

-- =============================================================================
-- AGOSTO
-- =============================================================================
(
    '08150000-0000-0000-0000-000000000815',
    'Assunção de Nossa Senhora aos Céus',
    'assuncao-de-nossa-senhora',
    'Solenidade Maior • Rainha Assunta ao Céu em Corpo e Alma',
    8, 15, '15 de Agosto',
    'A gloriosa elevação da Virgem Maria em corpo e alma à glória do Paraíso.',
    'Dogma proclamado pelo Papa Pio XII: Maria não sofreu a corrupção do sepulcro, sendo coroada Rainha de todo o Universo.',
    'Terminado o curso de sua vida terrena, a Imaculada Mãe de Deus foi assunta em corpo e alma à glória celestial pelos anjos do Senhor. Este mistério antecipa para toda a Igreja a nossa esperança da ressurreição da carne no último dia.',
    'Toda a Cristandade e Esperança dos Cristãos',
    'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&q=80&w=800',
    'Deus eterno e todo-poderoso, que elevastes em corpo e alma à glória celeste a Imaculada Virgem Maria, Mãe do vosso Filho, concedei-nos aspirar sempre às coisas do alto. Amém.',
    ARRAY['Apareceu no céu um grande sinal: uma Mulher vestida de sol, com a lua sob os pés e na cabeça uma coroa de doze estrelas.'],
    true
),
(
    '08270000-0000-0000-0000-000000000827',
    'Santa Mônica',
    'santa-monica-mae-de-santo-agostinho',
    'Memória Litúrgica • Padroeira das Mães Cristãs',
    8, 27, '27 de Agosto',
    'Exemplo sublime de perseverança na oração e lágrimas que geraram a conversão de Santo Agostinho.',
    'Rezou e chorou durante 30 anos sem esmorecer até ver seu filho abraçar o batismo e a santidade católica.',
    'Nascida em Tagaste no norte da África, suportou com mansidão heroica o temperamento difícil do marido e os desvios morais do filho Agostinho. Ouviu de um santo bispo a profética frase: "Vai em paz, mulher, pois é impossível que se perca um filho de tantas lágrimas!".',
    'Mães Cristãs, Esposas e Famílias em Dificuldade',
    'https://images.unsplash.com/photo-1548625361-195979bc7583?auto=format&fit=crop&q=80&w=800',
    'Senhor, que consolastes Santa Mônica concedendo-lhe a conversão de seu filho Agostinho, dai-nos chorar os nossos pecados com sincero coração. Amém.',
    ARRAY['Uma só coisa me fazia desejar viver mais um pouco: ver-te cristão católico antes de morrer.'],
    false
),
(
    '08280000-0000-0000-0000-000000000828',
    'Santo Agostinho de Hipona',
    'santo-agostinho-bispo-doutor',
    'Bispo e Doutor da Graça • Padre da Igreja',
    8, 28, '28 de Agosto',
    'Uma das maiores inteligências da história humana e mestre da graça e do amor de Deus.',
    'Autor de "Confissões" e "A Cidade de Deus", converteu-se pelo batismo ministrado por Santo Ambrósio.',
    'Nascido em Tagaste em 354, após anos de busca inquietante nas paixões e filosofias errôneas, ouviu a voz celestial "Tolle, Lege!" (Toma e lê) na Epístola aos Romanos. Batizado em Milão, tornou-se Bispo de Hipona e o maior teólogo dos primeiros séculos cristãos.',
    'Teólogos, Filósofos e Tipógrafos',
    'https://images.unsplash.com/photo-1519817650390-64a93db51149?auto=format&fit=crop&q=80&w=800',
    'Tarde te amei, ó Beleza tão antiga e tão nova, tarde te amei! Eis que habitavas dentro de mim e eu te procurava fora. Chamaste, clamaste e rompeste a minha surdez. Amém.',
    ARRAY['Fizeste-nos, Senhor, para Ti, e inquieto está o nosso coração enquanto não repousar em Ti.', 'A medida do amor é amar sem medida.'],
    true
),

-- =============================================================================
-- SETEMBRO
-- =============================================================================
(
    '09140000-0000-0000-0000-000000000914',
    'Exaltação da Santa Cruz',
    'exaltacao-da-santa-cruz',
    'Festa Litúrgica • O Troféu da Salvação',
    9, 14, '14 de Setembro',
    'Adoração ao lenho sagrado no qual Cristo operou a redenção da humanidade.',
    '"Nós, porém, devemos gloriar-nos na Cruz de Nosso Senhor Jesus Cristo, na qual está a nossa vida e ressurreição".',
    'Esta festa recorda a recuperação e exaltação da Vera Cruz de Cristo em Jerusalém e a dedicação da Basílica do Santo Sepulcro. A Cruz, antigo instrumento de suplício, tornou-se pela Paixão do Redentor o estandarte de vitória, glória e amor sem limites.',
    'Toda a Cristandade e Confrarias da Paixão',
    'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&q=80&w=800',
    'Ó Deus, que quisestes salvar a humanidade pelo sacrifício do vosso Filho na árvore da Cruz, concedei que, tendo conhecido na terra o seu mistério, alcancemos no céu os frutos da redenção. Amém.',
    ARRAY['Ave Crux, Spes Unica! (Salve, ó Cruz, esperança única!)'],
    true
),
(
    '09150000-0000-0000-0000-000000000915',
    'Nossa Senhora das Dores (Mater Dolorosa)',
    'nossa-senhora-das-dores',
    'Memória Litúrgica • Corredentora ao Pé da Cruz',
    9, 15, '15 de Setembro',
    'A compaixão da Virgem Maria ao pé da Cruz, unindo seu sofrimento ao do seu Filho divino.',
    'As Sete Dores de Maria nos ensinam o valor corredentor do sofrimento oferecido por amor a Deus.',
    'Junto à Cruz de Jesus estava de pé a sua Mãe (Stabat Mater). Conforme a profecia de Simeão, a espada de dor transpassou sua alma quando o Coração de Jesus foi aberto pela lança. Maria é o refúgio seguro para todos os corações aflitos e atribulados.',
    'Pessoas em Luto, Enfermos e Aflitos',
    'https://images.unsplash.com/photo-1548625361-195979bc7583?auto=format&fit=crop&q=80&w=800',
    'Ó Deus, que junto à Cruz do vosso Filho quisestes a presença da sua Mãe dolorosa, fazei que a vossa Igreja participe com Maria da Paixão de Cristo para merecer a sua ressurreição. Amém.',
    ARRAY['Ó vós todos que passais pelo caminho, olhai e vede se há dor semelhante à minha dor!'],
    true
),
(
    '09290000-0000-0000-0000-000000000929',
    'Santos Arcanjos Miguel, Gabriel e Rafael',
    'santos-arcanjos-miguel-gabriel-rafael',
    'Festa Litúrgica • Príncipes da Milícia Celeste',
    9, 29, '29 de Setembro',
    'Os três gloriosos Arcanjos mensageiros e guerreiros de Deus Pai.',
    'Miguel ("Quem como Deus?"), Gabriel ("Força de Deus") e Rafael ("Medicina de Deus").',
    'São Miguel expulsou Lúcifer do Céu e defende a Igreja em todos os combates; São Gabriel anunciou a Encarnação do Verbo à Virgem Maria e o nascimento de João Batista; São Rafael curou a cegueira de Tobit e guiou Tobias em sua jornada segura.',
    'Policiais, Paramédicos, Mensageiros e Viajantes',
    'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=800',
    'São Miguel Arcanjo, defendei-nos no combate, sede o nosso refúgio contra as maldades e ciladas do demônio. Ordene-lhe Deus, instantemente o pedimos, e vós, príncipe da milícia celeste, precipitai no inferno a satanás e a todos os espíritos malignos. Amém.',
    ARRAY['Quis ut Deus? (Quem como Deus?)'],
    true
),
(
    '09300000-0000-0000-0000-000000000930',
    'São Jerônimo',
    'sao-jeronimo-presbitero-doutor',
    'Presbítero e Doutor da Igreja • Tradutor da Vulgata',
    9, 30, '30 de Setembro',
    'O grande tradutor das Sagradas Escrituras dos textos originais para o latim (Vulgata).',
    '"Ignorar as Escrituras é ignorar a Cristo". Dedicou sua vida ao estudo bíblico na gruta de Belém.',
    'Nascido na Dalmácia em 347, monge e secretário do Papa São Dâmaso, recebeu a missão monumental de traduzir a Bíblia inteira do hebraico, aramaico e grego para o latim. Viveu décadas em penitência austera e oração perpétua na gruta onde Jesus nasceu em Belém.',
    'Biblistas, Tradutores, Estudiosos e Arqueólogos',
    'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&q=80&w=800',
    'Ó Deus, que destes a São Jerônimo um profundo amor pela vossa Palavra, fazei que o vosso povo se alimente com mais abundância das Sagradas Escrituras e encontre nelas a fonte da vida. Amém.',
    ARRAY['Ignorar as Sagradas Escrituras é ignorar o próprio Cristo Jesus.'],
    false
),

-- =============================================================================
-- OUTUBRO
-- =============================================================================
(
    '10010000-0000-0000-0000-000000001001',
    'Santa Teresinha do Menino Jesus',
    'santa-teresinha-do-menino-jesus',
    'Virgem e Doutora da Igreja • Padroeira das Missões',
    10, 1, '1 de Outubro',
    'A mestra da Pequena Via da infância espiritual que prometeu uma chuva de rosas do céu.',
    'No coração da Igreja, minha Mãe, eu serei o Amor. Ensinou o abandono confiante nos braços do Pai.',
    'Nascida em Alençon em 1873, ingressou aos 15 anos no Carmelo de Lisieux. Sem nunca ter saído da clausura, foi proclamada por São Pio X a maior santa dos tempos modernos e Padroeira das Missões. Sua autobiografia "História de uma Alma" tocou milhões de corações pela simplicidade do amor cotidiano.',
    'Missões, Floristas, Doentes de Tuberculose e Aviadores',
    'https://images.unsplash.com/photo-1548625361-195979bc7583?auto=format&fit=crop&q=80&w=800',
    'Ó Deus, que abris o vosso Reino aos pequeninos e humildes, dai-nos seguir com confiança o caminho de Santa Teresinha para que alcancemos a vossa glória eterna. Amém.',
    ARRAY['No coração da Igreja, minha Mãe, eu serei o Amor!', 'Passarei o meu céu fazendo o bem sobre a terra.'],
    true
),
(
    '10040000-0000-0000-0000-000000001004',
    'São Francisco de Assis',
    'sao-francisco-de-assis',
    'Fundador da Ordem dos Frades Menores • O Poverello',
    10, 4, '4 de Outubro',
    'O amante da Dama Pobreza que recebeu em seu corpo os Estigmas da Paixão de Cristo.',
    '"Francisco, vai e restaura a minha Igreja". Apóstolo da paz evangélica e do amor fraterno a toda a criação.',
    'Nascido em Assis em 1181, despiu-se de todas as riquezas paternas para abraçar o Evangelho com fidelidade absoluta. Fundou a Ordem Franciscana, criou o primeiro Presépio em Greccio e compôs o Cântico das Criaturas. Foi o primeiro santo a receber as chagas visíveis de Cristo em seu corpo.',
    'Ecologia, Animais, Franciscanos e Paz',
    'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=800',
    'Senhor, fazei-me instrumento de vossa paz. Onde houver ódio, que eu leve o amor; onde houver ofensa, que eu leve o perdão; onde houver trevas, que eu leve a luz. Amém.',
    ARRAY['Comece fazendo o que é necessário, depois o que é possível, e de repente você estará fazendo o impossível.'],
    true
),
(
    '10120000-0000-0000-0000-000000001012',
    'Nossa Senhora da Conceição Aparecida',
    'nossa-senhora-aparecida-padroeira-do-brasil',
    'Solenidade Maior • Rainha e Padroeira do Brasil',
    10, 12, '12 de Outubro',
    'A imagem milagrosa da Mãe de Deus resgatada nas águas do Rio Paraíba do Sul em 1717.',
    'Sinal perpétuo de consolo, esperança e união para todo o povo brasileiro.',
    'Três humildes pescadores encontraram primeiro o corpo e depois a cabeça da imagem escura de Nossa Senhora da Conceição em suas redes. Seguiu-se uma pesca abundante e inúmeros milagres que reuniram o Brasil sob o manto azul da Mãe Aparecida.',
    'Brasil e Povo Brasileiro',
    'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&q=80&w=800',
    'Ó Virgem Maria, Senhora Aparecida, abençoai as nossas famílias, protegei o nosso Brasil e guiai os nossos passos para Jesus. Amém.',
    ARRAY['Aparecida das águas para abençoar a nossa terra e o nosso povo.'],
    true
),
(
    '10150000-0000-0000-0000-000000001015',
    'Santa Teresa de Jesus (de Ávila)',
    'santa-teresa-de-avila',
    'Virgem e Doutora da Igreja • Reformadora do Carmelo',
    10, 15, '15 de Outubro',
    'Mestra da oração mental e mística sublime da união com Deus.',
    '"Nada te turbe, nada te espante, tudo passa, Deus não muda. Só Deus basta!".',
    'Nascida em Ávila em 1515, reformou a Ordem Carmelita Descalça junto com São João da Cruz. Autora de obras-primas como "O Castelo Interior" e "Caminho de Perfeição", é a primeira mulher proclamada Doutora da Igreja pela profundidade incomparável de sua doutrina espiritual.',
    'Espanha, Escritores e Mestres de Oração',
    'https://images.unsplash.com/photo-1519817650390-64a93db51149?auto=format&fit=crop&q=80&w=800',
    'Nada te turbe, nada te espante, tudo passa, Deus não muda; a paciência tudo alcança; quem a Deus tem, nada lhe falta: Só Deus basta! Amém.',
    ARRAY['Só Deus basta!', 'A oração é um trato de amizade com Aquele que sabemos que nos ama.'],
    true
),

-- =============================================================================
-- NOVEMBRO
-- =============================================================================
(
    '11010000-0000-0000-0000-000000001101',
    'Solenidade de Todos os Santos',
    'solenidade-de-todos-os-santos',
    'Solenidade Maior • A Igreja Triunfante no Céu',
    11, 1, '1 de Novembro',
    'A multidão inumerável dos santos que contemplam face a face a Deus no Céu.',
    'Celebração de todos os bem-aventurados conhecidos e desconhecidos que lavaram suas vestes no Sangue do Cordeiro.',
    'Nesta solenidade festiva, a Igreja terrena une-se à Igreja Celeste para contemplar a comunhão dos santos. Recorda-nos a vocação universal à santidade de todos os batizados, ensinando que a santidade é o único e verdadeiro sucesso da existência humana.',
    'Toda a Humanidade e Vocação à Santidade',
    'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&q=80&w=800',
    'Deus eterno e todo-poderoso, que nos concedeis celebrar numa só festa os méritos de Todos os Santos, dai-nos pela intercessão de tantos irmãos a plenitude da vossa graça. Amém.',
    ARRAY['Vi uma grande multidão que ninguém podia contar, de todas as nações, tribos e línguas.'],
    true
),
(
    '11020000-0000-0000-0000-000000001102',
    'Comemoração de Todos os Fiéis Defuntos',
    'comemoracao-de-todos-os-fieis-defuntos',
    'Comemoração Litúrgica • A Igreja Padecente',
    11, 2, '2 de Novembro',
    'Oração e sufrágio da Santa Missa pelas almas benditas do Purgatório.',
    '"Santo e salutar pensamento é orar pelos mortos para que sejam livres de seus pecados" (2 Mac 12, 46).',
    'A Igreja dedica este dia à oração, indulgências e oferecimento do Santo Sacrifício da Missa pelas almas que se purificam no Purgatório a caminho da glória beatífica. Recorda-nos a transitoriedade da vida e a caridade na comunhão dos santos.',
    'Almas do Purgatório e Pessoas Enlutadas',
    'https://images.unsplash.com/photo-1548625361-195979bc7583?auto=format&fit=crop&q=80&w=800',
    'Dai-lhes, Senhor, o repouso eterno, e brilhe para eles a vossa luz perpétua. Descansem em paz. Amém.',
    ARRAY['Eu sou a Ressurreição e a Vida; quem crê em mim, ainda que esteja morto, viverá.'],
    false
),
(
    '11270000-0000-0000-0000-000000001127',
    'Nossa Senhora das Graças e a Medalha Milagrosa',
    'nossa-senhora-das-gracas-medalha-milagrosa',
    'Memória Litúrgica • Dispensadora de Todas as Graças',
    11, 27, '27 de Novembro',
    'Aparições da Virgem Maria a Santa Catarina Labouré na Rue du Bac em Paris (1830).',
    '"Ó Maria concebida sem pecado, rogai por nós que recorremos a vós". Raios de luz emanando de suas mãos como graças para quem as pede.',
    'Em 1830, Nossa Senhora revelou o modelo da Medalha Milagrosa a Santa Catarina Labouré, prometendo abundantes graças àqueles que a usarem com fé ao pescoço. A rápida difusão e os incontáveis prodígios prepararam a proclamação do dogma da Imaculada Conceição em 1854.',
    'Enfermos, Famílias e Toda a Cristandade',
    'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=800',
    'Ó Maria concebida sem pecado, rogai por nós que recorremos a vós. Fazei cair sobre nós os raios luminosos das vossas graças celestiais. Amém.',
    ARRAY['Estes raios são o símbolo das graças que derramo sobre as pessoas que me pedem.'],
    true
),

-- =============================================================================
-- DEZEMBRO
-- =============================================================================
(
    '12080000-0000-0000-0000-000000001208',
    'Imaculada Conceição da Santíssima Virgem Maria',
    'imaculada-conceicao-de-maria',
    'Solenidade Maior • Preservada de Toda Mancha de Pecado',
    12, 8, '8 de Dezembro',
    'Dogma de Fé: Maria foi preservada imune do pecado original desde o primeiro instante de sua conceição.',
    'Pela graça antecipada dos méritos da Redenção de Cristo, a Virgem é a Cheia de Graça, a Toda Pura.',
    'Proclamado solenemente pelo Beato Papa Pio IX na Bula Ineffabilis Deus (1854), este dogma celebra que Maria Santíssima foi cumulada de todas as graças divinas para ser o Templo puríssimo do Filho de Deus. É o modelo supremo da santidade da Igreja.',
    'Toda a Cristandade, Estados Unidos e Portugal',
    'https://images.unsplash.com/photo-1544644181-1484b3fdfc62?auto=format&fit=crop&q=80&w=800',
    'Ó Deus, que pela Imaculada Conceição da Virgem preparastes para o vosso Filho digna morada, concedei que, preservada de todo pecado pelos méritos de Cristo, cheguemos puros à vossa presença. Amém.',
    ARRAY['Ave Maria, cheia de graça, o Senhor é convosco!', 'Toda formosa és, Maria, e em ti não há mancha de pecado!'],
    true
),
(
    '12120000-0000-0000-0000-000000001212',
    'Nossa Senhora de Guadalupe',
    'nossa-senhora-de-guadalupe',
    'Festa Litúrgica • Imperatriz e Padroeira de Toda a América',
    12, 12, '12 de Dezembro',
    'A Mãe Morena apareceu a São Juan Diego na colina de Tepeyac em 1531, deixando sua imagem no manto (tilma).',
    '"Não estou eu aqui, que sou tua Mãe?". Converteu mais de 8 milhões de indígenas à fé católica.',
    'A Virgem de Guadalupe apareceu como uma jovem indígena grávida do Salvador, reconciliando povos e encerrando os sacrifícios humanos no México. Seu manto miraculoso de fibra de cacto, conservado intacto há quase 500 anos, desafia todas as explicações da ciência moderna.',
    'Américas, Nascituros e Defesa da Vida',
    'https://images.unsplash.com/photo-1548625361-195979bc7583?auto=format&fit=crop&q=80&w=800',
    'Ó Virgem de Guadalupe, Mãe das Américas, olhai para os vossos filhos, protegei as nossas famílias e defendei a vida desde a sua concepção. Amém.',
    ARRAY['Não estou eu aqui, que sou tua Mãe? Estás sob a minha sombra e meu amparo.'],
    true
),
(
    '12250000-0000-0000-0000-000000001225',
    'Natal de Nosso Senhor Jesus Cristo',
    'natal-de-nosso-senhor-jesus-cristo',
    'Solenidade Maior • O Nascimento do Salvador',
    12, 25, '25 de Dezembro',
    'O Deus Infinito nasce Menino em Belém na manjedoura para a nossa salvação.',
    '"Glória a Deus nas alturas e paz na terra aos homens por Ele amados!". O Emanuel, Deus conosco.',
    'No silêncio da noite santa em Belém, a Virgem Maria dá à luz o Salvador do mundo, envolvendo-o em panos e deitando-o na manjedoura. Os coros angélicos entoam o Glória aos pastores, e a luz eterna dissipa as trevas do pecado.',
    'Toda a Humanidade, Famílias e Crianças',
    'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&q=80&w=800',
    'Ó Deus, que admiravelmente criastes a dignidade da natureza humana e mais admiravelmente a restaurastes, concedei-nos participar da divindade daquele que se dignou assumir a nossa humanidade. Amém.',
    ARRAY['Um Menino nos nasceu, um Filho nos foi dado! Seu nome é Príncipe da Paz.'],
    true
),
(
    '12260000-0000-0000-0000-000000001226',
    'Santo Estêvão Protomártir',
    'santo-estevao-protomartir',
    'Festa Litúrgica • Primeiro Mártir da Cristandade',
    12, 26, '26 de Dezembro',
    'Diácono cheio de graça e fortaleza, o primeiro mártir a derramar o sangue por Cristo.',
    'Ao ser apedrejado, contemplou os céus abertos e perdoou seus algozes: "Senhor, não lhes imputeis este pecado!".',
    'Escolhido pelos Apóstolos como um dos sete primeiros diáconos para servir às mesas e pregar o Evangelho, Estêvão realizava grandes prodígios em Jerusalém. Levado perante o Sinédrio, deu um testemunho profético sublime e morreu como Jesus, perdoando quem o apedrejava. Saulo guardava as vestes dos algozes.',
    'Diáconos, Pedreiros e Servidores da Caridade',
    'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&q=80&w=800',
    'Concedei-nos, Senhor, imitar o que celebramos, para que aprendamos a amar também os nossos inimigos, pois comemoramos o nascimento celeste daquele que soube orar pelos próprios perseguidores. Amém.',
    ARRAY['Vejo os céus abertos e o Filho do Homem de pé à direita de Deus!'],
    false
),
(
    '12270000-0000-0000-0000-000000001227',
    'São João Evangelista',
    'sao-joao-apostolo-e-evangelista',
    'Festa Litúrgica • O Discípulo Amado',
    12, 27, '27 de Dezembro',
    'O apóstolo que reclinou a cabeça no peito de Jesus e recebeu Maria como Mãe ao pé da Cruz.',
    'Autor do quarto Evangelho, das três Cartas e do Livro do Apocalipse. O apóstolo do Amor Divino.',
    'O mais jovem dos doze apóstolos, permaneceu fiel ao lado da Virgem Maria na hora da Crucificação. No Calvário, Jesus lhe confiou a Mãe: "Filho, eis aí a tua Mãe!". Viveu até idade avançada em Éfeso e no exílio de Patmos, ensinando incessantemente: "Filhinhos, amai-vos uns aos outros".',
    'Teólogos, Escritores, Editores e Amizade Verdadeira',
    'https://images.unsplash.com/photo-1519817650390-64a93db51149?auto=format&fit=crop&q=80&w=800',
    'Ó Deus, que pelos ensinamentos de São João Apóstolo e Evangelista nos revelastes os mistérios do vosso Verbo, dai-nos compreender com a mente e o coração a grandeza da sua mensagem. Amém.',
    ARRAY['Deus é Amor: quem permanece no amor permanece em Deus e Deus nele.'],
    true
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    title = EXCLUDED.title,
    feast_month = EXCLUDED.feast_month,
    feast_day = EXCLUDED.feast_day,
    feast_date = EXCLUDED.feast_date,
    short_bio = EXCLUDED.short_bio,
    summary = EXCLUDED.summary,
    full_bio = EXCLUDED.full_bio,
    patronage = EXCLUDED.patronage,
    image_url = EXCLUDED.image_url,
    prayer = EXCLUDED.prayer,
    quotes = EXCLUDED.quotes,
    featured = EXCLUDED.featured;
